name: Java Selenium Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Maven Test
        run: mvn clean test

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: reports/ExtentReport.html

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: SurefireReports
          path: target/surefire-reports